[package]
name = "chesster"
version = "0.1.0"
edition = "2021"

[dependencies]
const_for = "0.1.5"
rand = "0.9.0"
rand_chacha = "0.9.0"
raylib = "5.0.2"

[profile.release]
debug = true

[profile.release-max]
inherits = "release"
lto = true
